name: Daily Code Challenge Automation

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8 AM UTC
  workflow_dispatch:

jobs:
  run-challenge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Challenge Script
        run: |
          echo "Starting daily code challenge"
          # Replace this with your challenge script
          python challenge.py

      - name: Commit and Push Results
        run: |
          git config --local user.email "brandonlum17@gmail.com"
          git config --local user.name "bryzle"
          git add .
          git commit -m "Daily Challenge: $(date)"
          git push
